@startuml

class connect4{
    - boardView
    - yesNoDialog
    + playGame()
}
class yesNoDialogView{
    + read(message)
    + isAffirmative()
}
class board{
    - tokens[]
    - inLine
    - lastToken
    + reset(maxRows, maxColumns)
    + isFilledColumn(column)
    + putToken(column, color)
    + getFirstEmptyRowFromColumn(column)
    + isEndGame()
    + isFilled()
    + isInLineToken(tokens[])
    + getTokens()
}
class boardView{
    - MAX_ROWS
    - MAX_COLUMNS
    - Board
    - TurnView
    + init()
    + show()
}
class inLine{
    - tokens
    - IN_LINE_NUMBER_OF_TOKENS
    + isInLineToken(tokens[], token)
    - isInLineHorizontal(token)
    - isInLineVertical(token)
    - isInLineDiagonal(token)
    - isInLineReverseDiagonal(token)
    - isColorOnPosition(token)
}

class token{
    - Color
    - coordinate
    + getColor()
    + getRow()
    + getColumn()
}

class coordinate {
    - row 
    - column
    + getRow()
    + getColumn()
}

class turnView{
    - turn
    + getColumn(maxColumns)
    + nextTurn()
    + getColor()
}

class turn{
    - color
    + getColor()
    + nextTurn()
}

enum colors{
Red
Yellow
}

connect4 ..> boardView
connect4 ..> yesNoDialogView
boardView *--> board
boardView ..> turnView
turnView o--> turn
board o--> token
board o--> inLine
board ..> coordinate
inLine ..> colors
turn o--> colors
token *--> colors
token *--> coordinate
@enduml